<script>
    require([
        'jquery',
        'owlcarousel',
        'domReady!'
    ], function ($) {
        $("#czonetech-owl-carousel-<?php echo $block->getData('slider_id');?>").owlCarousel({
            nav: <?php echo $block->getData('show_slide_navigation_controls')? 'true': 'false';?>,
            dots: <?php echo $block->getData('show_slide_pagination_controls')? 'true': 'false';?>,
            loop: true,
            autoplay: <?php echo $block->getData('slide_auto_play_animation')? 'true': 'false';?>,
            margin: 10,
            center: true,
            autoplaySpeed: <?php echo $block->getData('slide_animation_speed');?>,
            autoplayTimeout: <?php echo $block->getData('slide_animation_interval');?>,
            autoplayHoverPause: <?php echo $block->getData('slide_pause_animation_on_hover')? 'true': 'false';?>,
            responsive:{
                0 : {
                    items: <?php echo $block->getData('slide_count_mobile');?>
                },

                768 : {
                    items: <?php echo $block->getData('slide_count_tablet');?>
                },

                992 : {
                    items: <?php echo $block->getData('slide_count_desktop_small');?>
                },

                1200 : {
                    items: <?php echo $block->getData('slide_count_desktop');?>
                }
            }
        });
    })

</script>
<?php
/**
 * @var $block \CzoneTech\Slider\Block\Widget\Slider\Block
 */
$items = $block->getSliderItems();?>
<div id="czonetech-owl-carousel-<?php echo $block->getData('slider_id');?>" class="<?php echo $block->getData('slide_wrapper_class');?> owl-carousel">
<?php foreach($items as $item):?>
<div>
    <?php if($item->getTitle()):?>
        <div class="slide-item-title"><?php echo $block->escapeHtml($item->getTitle());?></div>
    <?php endif;?>
    <?php if($block->getContentType() == \CzoneTech\Slider\Model\Slider::CONTENT_TYPE_IMAGE):?>
        <?php if($item->getImageUrl()):?>
        <img src="<?php echo $block->escapeHtml($item->getImageUrl());?>" />
        <?php endif;?>
    <?php elseif($block->getContentType() == \CzoneTech\Slider\Model\Slider::CONTENT_TYPE_CUSTOM):?>
        <?php echo $block->getFilterProvider()->getBlockFilter()->filter($item->getContent());?>
    <?php endif;?>
</div>
<?php endforeach;?>
</div>
